### ISSUE TITLE
Store models in a proper format

### ISSUE THREAD

**Issue by kamilzyla** [Appsilon/mbaza#238]
Currently our models are stored in Python pickle format, which has severe consequences:
1. To restore the pickle, the Python environment must match exactly the one used to create the Pickle. We are unable to update Python packages without risking a break.
2. The dependencies of the pickle are effectively hidden. Packaging models for Windows is a huge pain and everybody seems to have different issues. Setting up the Windows environment takes 4-8 hours each time (from experience) and is hardly reproducible.
3. Our packaged models are probably much bigger (perhaps 5x, currently at ~800 MB) than necessary, as they include ALL the libraries which were needed during development.
4. Due to all reasons above, it is difficult to introduce a better dependency management solution, like Pipenv.

There are formats designed specifically to store trained models, which can then be explicitly loaded into the library and are likely to offer more backwards compatibility.

**Comment by kamilzyla** [comment]
Models in ONNX format can be found in the [mbaza-ml](https://github.com/Appsilon/mbaza-ml) repository.

**Comment by pstorozenko** [comment]
I'm working currently on porting Serengeti model to onnx format.
For some reason I wasn't able to create environment using [requirements.txt](https://github.com/Appsilon/mbaza/blob/v1.3.1/models/runner/requirements.txt) file with `python>=3.6` ¯\\_(ツ)\_/¯
For porting purpose I'm working with python 3.6.13 and just 
```sh
pip install fastai==1.0.61 torch==1.5.0 numpy pandas onnxruntime
```

**Comment by pstorozenko** [comment]
Onnx models shared on Slack, I can upload them in a proper place but I don't know where. 
Inference script also attached
Results checked for [east_african_savannas](https://github.com/Appsilon/mbaza/tree/v1.3.1/models/east_african_savannas) model.
They should be also correct for [central_african_forests](https://github.com/Appsilon/mbaza/tree/v1.3.1/models/central_african_forests), I'll double check it later.

After TONS of debugging I've finally discovered what makes predictions form onnx models and fastai different.
@swiezew fastai uses sigmoid instead of softmax as activation in the last layer ¯\\\_(ツ)\_/¯
Now they're almost the same:
![image](https://user-images.githubusercontent.com/9080845/186444790-ffb30df0-a772-4eef-bc4c-3dad6825479e.png)

![image](https://user-images.githubusercontent.com/9080845/186445210-294f4cac-2da6-4ab3-8d00-1475d6df59c8.png)


[requirements_onnx_export.txt](https://github.com/Appsilon/mbaza/files/9416833/requirements_onnx_export.txt)

[export_onnx.txt](https://github.com/Appsilon/mbaza/files/9416839/export_onnx.txt)

[inference_onnx.txt](https://github.com/Appsilon/mbaza/files/9416865/inference_onnx.txt)

**Comment by pstorozenko** [comment]
@kamilzyla 
Please follow the `inference_onnx` script from above for inference, note that normalization step is **already included** in onnx.
